# Database connection details from environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Puerto de la aplicación Spring Boot
server.port=${PORT:8080}

# Esto evita que Hibernate intente validar cosas antes de conectar
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Especificar el dialecto de la base de datos
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Desabilitar la advertencia de open-in-view
spring.jpa.open-in-view=false