spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:44WkozoFm53u2Cp.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:jb1oDtqHbG3Oe3iD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=8080
jwt.secret=${JWT_SECRET:secret}
jwt.expiration=360000
spring.main.allow-bean-definition-overriding=true