# Database connection details from environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Puerto de la aplicacin Spring Boot
server.port=${PORT:8080}

# 'create' dropea y recrea el esquema al inicio. Usar para corregir la estructura de la tabla.
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false
