# --- CONFIGURACI�N DE BASE DE DATOS (TiDB Cloud) ---
# Si las variables de entorno no est�n en Render, usar� los valores despu�s de los dos puntos (:)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:44WkozoFm53u2Cp.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:jb1oDtqHbG3Oe3iD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Forzamos el dialecto para evitar errores de detecci�n autom�tica
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# --- CONFIGURACI�N DEL SERVIDOR ---
# Render asigna din�micamente el puerto; si no, usa el 8080
server.port=${PORT:8080}

# --- SEGURIDAD Y JWT ---
# Cambia 'secret' por una clave larga y segura en las variables de Render
jwt.secret=${JWT_SECRET:secret}
jwt.expiration=360000

# Permitir sobrescribir definiciones de beans si es necesario
spring.main.allow-bean-definition-overriding=true