# Aiven MySQL connection
spring.datasource.url=jdbc:mysql://mysql-2d67550b-viuntifrancisco-6077.d.aivencloud.com:11909/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_A0Sf0SATFvl1QLfsw_f

# Puerto de la aplicación Spring Boot
server.port=${PORT:8080}

# Esto evita que Hibernate intente validar cosas antes de conectar
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Especificar el dialecto de la base de datos
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Desabilitar la advertencia de open-in-view
spring.jpa.open-in-view=false